server:
  port: 8080
  servlet:
    context-path: /yangfei
#
#spring:
#  profiles:
#    active: prod
#
#
#logging:
#  level:
#    root: info
#    com:
#      yf:
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}-%msg%n'
#    dateformat: -yyyy-MM-dd HH:mm:ss.SSS
#  file:
#    name: D:/log/yangfei
#  logback:
#    rollingpolicy:
#      max-file-size: 2KB
##    path: D:/
#
