server:
  port: 8080
  servlet:
    context-path: /yangfei


#通过属性设置确定扫描静态路径地址
spring:
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

  mvc:
    view:
      suffix: .html
      prefix: /pages/


#  mvc:
#    format:
#      date: yyyy/MM/dd

#
#spring:
#  profiles:
#    active: prod
#
#
#logging:
#  level:
#    root: info
#    com:
#      yf:
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}-%msg%n'
#    dateformat: -yyyy-MM-dd HH:mm:ss.SSS
#  file:
#    name: D:/log/yangfei
#  logback:
#    rollingpolicy:
#      max-file-size: 2KB
##    path: D:/
#

